
stages:
  - build
  - test
  - deploy

build:
  stage: build
  needs: []
  script:
    - python --version > py-ver.log
    - pip install wheel
    - python setup.py sdist bdist_wheel > package.log 
    - pip install --log pip.log --find-links ./dist/ mcvqoe-nist sphinx numpydoc unittest-xml-reporting > install.log 
  artifacts:
      when: always
      paths:
        - package.log
        - py-ver.log
        - install.log
        - pip.log
        - dist/*.whl
        - mcvqoe/version.py

test-math:
  stage: test
  script:
    - python tests/test_math.py

test-log:
  stage: test
  script:
    - python tests/test_log.py
      
test-sim:
  stage: test
  script:
    - python tests/sim_test.py
      
test-testCpy:
  stage: test
  script:
    - python tests/test_testCpy.py
      
pages:
  stage: deploy
  script:
    - sphinx-build -b html ./docs/source/ public
  only:
    - develop
    - sphinx
  artifacts:
    paths:
      - public
