
stages:
  - build
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

image: python:3.8

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - source /venv/bin/activate

build:
  stage: build
  before_script:
    -
  script:
    - pip install virtualenv
    - virtualenv venv
    - source /venv/bin/activate
    - pip install .
    - pip install xmlrunner

test-math:
  stage: test
  script:
    - python tests/test_math.py
  artifacts :
    when: always
    paths:
      - math-tests.xml
    reports:
      junit: math-tests.xml

test-log:
  stage: test
  script:
    - python tests/test_log.py

test-sim:
  stage: test
  script:
    - python tests/sim_test.py

test-testCpy:
  stage: test
  script:
    - python tests/test_testCpy.py

test-ITS-delay:
  stage: test
  script:
    - python tests/test_ITS_delay.py
  artifacts :
    when: always
    paths:
      - ITS-tests.xml
    reports:
      junit: ITS-tests.xml

pages:
  stage: deploy
  script:
    - sphinx-build -b html ./docs/source/ public
  only:
    - develop
    - sphinx
  artifacts:
    paths:
      - public
