
stages:
  - build
  - test

build:
  stage: build
  script:
    - python --version > py-ver.log
    - python setup.py sdist bdist_wheel > package.log 
  artifacts:
      when: always
      paths:
        - package.log
        - py-ver.log
        - dist/*.whl

test-math:
  stage: test
  script:
    - python -m venv test-env > env.log
    - test-env/bin/pip install --log pip.log --find-links ./dist/ mcvqoe-nist > install.log 
    - test-env/bin/python tests/test_math.py > mathtest.log 
  artifacts:
      when: always
      paths:
        - pip.log
        - env.log
        - mathtest.log
        - install.log
        - test-env/*
