
stages:
  - build
  - venv
  - test

build:
  stage: build
  needs: []
  script:
    - python --version > py-ver.log
    - python setup.py sdist bdist_wheel > package.log 
  artifacts:
      when: always
      paths:
        - package.log
        - py-ver.log
        - dist/*.whl

venv:
  stage: venv
  needs: [build]
  script:
    - python -m venv test-env > env.log
    - test-env/bin/pip install --log pip.log --find-links ./dist/ mcvqoe-nist > install.log 
  artifacts:
      when: always
      paths:
        - pip.log
        - env.log
        - install.log
        - test-env/*


test-math:
  stage: test
  needs: [venv]
  script:
    - test-env/bin/python tests/test_math.py

test-log:
  stage: test
  needs: [venv]
  script:
    - test-env/bin/python tests/test_log.py
